[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = spiffs
lib_deps = 
	me-no-dev/AsyncTCP @ ^1.1.1
	me-no-dev/ESP Async WebServer @ ^1.2.3
	knolleary/PubSubClient @ ^2.8
	ayushsharma82/AsyncElegantOTA @ ^2.2.8